services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:${WEB_PORT_INTERNAL}
    volumes:
      - .:/app
    ports:
      - "${WEB_PORT_EXTERNAL}:${WEB_PORT_INTERNAL}"
    depends_on:
      - redis

  redis:
    image: redis:7
    ports:
      - "${REDIS_PORT_EXTERNAL}:${REDIS_PORT_INTERNAL}"

  celery:
    build: .
    command: celery -A config worker -l info
    volumes:
      - .:/app
    depends_on:
      - redis
      - web

  celery-beat:
    build: .
    command: celery -A config beat -l info
    volumes:
      - .:/app
    depends_on:
      - redis
      - web